spring:
#  cloud:
#    gateway:
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:3000"
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#            allowedHeaders:
#              - Authorization
#              - Content-Type
#            allowCredentials: true

  application:
    name: api-gateway
  config:
    import: configserver:http://localhost:8888