version: '3'

services:
  db:
    image: postgres:15-alpine3.18
    restart: always
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=music_admin
      - POSTGRES_PASSWORD=music_password
      - POSTGRES_DB=music_db
#
#  redis:
#    image: redis:latest
#    restart: always
#    ports:
#      - "6379:6379"
#    environment:
#      - REDIS_PASSWORD=my-password
#      - REDIS_PORT=6379
#      - REDIS_DATABASES=16
#
#  zookeeper:
#    image: docker.io/bitnami/zookeeper:3.9
#    ports:
#      - "2181:2181"
#    volumes:
#      - "zookeeper_data:/bitnami"
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#
#  kafka:
#    image: docker.io/bitnami/kafka:3.4
#    ports:
#      - "9092:9092"
#    volumes:
#      - "kafka_data:/bitnami"
#    environment:
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#    depends_on:
#      - zookeeper