server:
  port: 8080
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost

spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-is: true
      routes:
        - id: player-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/player/**
          filters:
            - AuthenticationFilter

        - id: music-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/musify/audios/**
          filters:
            - AuthenticationFilter

        - id: user-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/auth/**

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970