name: Build and Push Docker Images

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api-gateway, config-server, eureka-server, music-service, player-service, user-service]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Output Java version
        run: java -version

      - name: Build the service
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Find all .jar files in the repository
        run: find . -name "*.jar"

      - name: Find all application.yml files in the repository
        run: find . -name "application.yml"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./${{ matrix.service }}/
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          provenance: mode=max
          tags: muzify/${{ matrix.service }}:latest
